export const ADD_FOOD_PLACE = 'ADD_FOOD_PLACE';
export const DELETE_FOOD_PLACE = 'DELETE_FOOD_PLACE';
export const SELECT_FOOD_PLACE = 'SELECT_FOOD_PLACE';
export const DESELECT_FOOD_PLACE = 'DESELECT_FOOD_PLACE';
